version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    networks:
      - dev
    volumes:
      - ./:/app
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  dev:
    external: true
